version: '1'

services:
  app1:
    image: 'myapp:1.0'
    ports:
      - '8080:8080'
    entrypoint:
      INST_NUM: 1
  app2:
      image: 'myapp:2.0'
      ports:
        - '8080:8080'
      entrypoint:
        INST_NUM: 2
      depends_on:
        - app1